### ISSUE TITLE
Unable to open magento from my browser

### ISSUE THREAD

**Issue by Tusharsb** [nefarioustim/vagrant-magento#2]
vagrant up went fine. But I wasn't sure 'what hostname' and 'what port' of nginx server was magento listening upon. To find out - I read the file /etc/nginx/sites-available/magento-vhost. It said that nginx server was made to listen for virtual hostname magento.nefariousdesigns.co.uk.

Hence I changed Vagrantfile to do port forwarding of my host machine's port 8000 to guest machine's port 80. And in my host machine changed /etc/hosts to contain the following line 

> 127.0.0.1       magento.nefariousdesigns.co.uk

After above improvements when I tried to open http://magento.nefariousdesigns.co.uk:8000/ in my browser it read '502 Bad Gateway' error.

Error log of nginx read the following

> 2015/09/27 09:15:22 [crit] 993#0: *20 connect() to unix:/var/run/php5-fpm.sock failed (13: Permission denied) while connecting to upstream, client: 10.0.2.2, server: magento.nefariousdesigns.co.uk, request: "GET / HTTP/1.1", upstream: "fastcgi://unix:/var/run/php5-fpm.sock:", host: "magento.nefariousdesigns.co.uk:8000"

Am i doing something wrong here ?

**Comment by nefarioustim** [comment]
First of all; sorry that you're having a bit of a nightmare with this. Also, thanks for that super-informative issue description!

The issue here is that PHP-FPM is refusing to take the forwarded PHP request from nginx due to permissions on the unix sock file. Having had a bit of a poke about regarding the error message you're seeing in your nginx error log, I suspect you need to update the following lines in the PHP-FPM configuration templates used by Puppet:

https://github.com/nefarioustim/vagrant-magento/blob/master/puppet/modules/php/templates/www.conf.erb#L44-L46

Uncomment and use the following values (assuming that your nginx webserver is running using the www-data user specified in the puppet configuration of this repo):

```
listen.owner = www-data
listen.group = www-data
listen.mode = 0660
```

Hopefully that helps. Unfortunately I don't have a test instance of this repo/vagrant box to test this on, so please let me know the outcome.

**Comment by nefarioustim** [comment]
Also, you shouldn't need to port-forward anything with the original configuration as it's set-up to use a static IP address for the box. This means that you could have just entered the following rule in your /etc/hosts file and accessed http://magento.nefariousdesigns.co.uk directly:

> 33.33.33.30 magento.nefariousdesigns.co.uk

However, I think your configuration changes have gotten you around that; I just thought I'd explain my original set-up. :)
